version: '3'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    extra_hosts:
      - "skapersk.42.fr:127.0.0.1"
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build: 
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
