version: '3'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql  # Monté sur le chemin par défaut de MariaDB

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build: 
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    # environment:
    #   - DOMAIN_NAME=skapersk.42.fr
    #   - MYSQL_DB=wordpress_db
    #   - MYSQL_USER=skapersk
    #   - MYSQL_PSW=Ki74Bh?,Bd78
    #   - MYSQL_DB_HOST=mariadb
    #   - MYSQL_ROOT_PSW=Xo78Gj!,Gh09
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
