services:
  nginx:
    networks:
      - inception
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: always

  mariadb:
    networks:
      - inception
    build: requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql  # Monté sur le chemin par défaut de MariaDB

  wordpress:
    networks:
      - inception
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/login/data/wordpress  # Changez ce chemin selon vos besoins
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/login/data/mariadb  # Changez ce chemin selon vos besoins

networks:
  inception:
    driver: bridge
