version: "3"

services:
  nginx:
    build: requirements/nginx/ 
    container_name: nginx 
    ports:
      - "443:443"         
    volumes:
      - ./web:/var/www/html
    restart: always
  # wp-php:
  #   build: requirements/wp-php/
  #   env_file: .env
  #   container_name: wp-php
  #   ports:
  #   - "443:443"
  #   restart: always 